### ISSUE TITLE
`TypeError:` Cannot read properties of undefined (reading 'roots')

### ISSUE THREAD

**Issue by RonBis** [volarjs/language-tools-starter#11]
Got this error from launched client on fresh installation.

<pre>
TypeError: Cannot read properties of undefined (reading 'roots')
    at Nu.createEmbeddedCodes (d:\html1\language-tools\packages\vscode\dist\server.js:1093:39919)
    at createEmbeddedCodes.next (<anonymous>)
    at new Nu (d:\html1\language-tools\packages\vscode\dist\server.js:1093:39731)
    at Object.createVirtualCode (d:\html1\language-tools\packages\vscode\dist\server.js:1093:39040)
    at Object.set (d:\html1\language-tools\packages\vscode\dist\server.js:2:11051)
    at d:\html1\language-tools\packages\vscode\dist\server.js:75:5729
    at Object.get (d:\html1\language-tools\packages\vscode\dist\server.js:2:10370)
    at fx (d:\html1\language-tools\packages\vscode\dist\server.js:2:30946)
    at E5 (d:\html1\language-tools\packages\vscode\dist\server.js:2:30811)
    at Object.findDocumentSymbols (d:\html1\language-tools\packages\vscode\dist\server.js:2:67746)
</pre>

**Comment by johnsoncodehk** [comment]
Fixed now, thanks for the report!
